version: "3.8"

networks:
  system:
    driver: bridge
services:
  postgresqldb:
    container_name: PostgresDB
    image: postgres
    restart: on-failure
    networks:
      - system
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb


